import json
from pathlib import Path

with open(Path(__file__).parent / "feature_info.json", "r") as f:
    feature_info = json.load(f)

RANGE_BAR_SHORT_TERM = "p0045"
RANGE_BAR_MID_TERM = "p009"
RANGE_BAR_LONG_TERM = "p018"

DOLLAR_BAR_SHORT_TERM = "15m"
DOLLAR_BAR_MID_TERM = "1h"
DOLLAR_BAR_LONG_TERM = "4h"

SIDE_RANGE_BAR_SHORT_FEATURES = feature_info["side"][RANGE_BAR_SHORT_TERM]
SIDE_RANGE_BAR_MID_FEATURES = feature_info["side"][RANGE_BAR_MID_TERM]
SIDE_RANGE_BAR_LONG_FEATURES = feature_info["side"][RANGE_BAR_LONG_TERM]
SIDE_DOLLAR_BAR_SHORT_FEATURES = feature_info["side"][DOLLAR_BAR_SHORT_TERM]
SIDE_DOLLAR_BAR_MID_FEATURES = feature_info["side"][DOLLAR_BAR_MID_TERM]
SIDE_DOLLAR_BAR_LONG_FEATURES = feature_info["side"][DOLLAR_BAR_LONG_TERM]

SIDE_RANGE_BAR_ALL = (
    SIDE_RANGE_BAR_SHORT_FEATURES
    + SIDE_RANGE_BAR_MID_FEATURES
    + SIDE_RANGE_BAR_LONG_FEATURES
)
SIDE_DOLLAR_BAR_ALL = (
    SIDE_DOLLAR_BAR_SHORT_FEATURES
    + SIDE_DOLLAR_BAR_MID_FEATURES
    + SIDE_DOLLAR_BAR_LONG_FEATURES
)
SIDE_ALL = SIDE_RANGE_BAR_ALL + SIDE_DOLLAR_BAR_ALL

META_RANGE_BAR_SHORT_FEATURES = feature_info["meta"][RANGE_BAR_SHORT_TERM]
META_RANGE_BAR_MID_FEATURES = feature_info["meta"][RANGE_BAR_MID_TERM]
META_RANGE_BAR_LONG_FEATURES = feature_info["meta"][RANGE_BAR_LONG_TERM]
META_DOLLAR_BAR_SHORT_FEATURES = feature_info["meta"][DOLLAR_BAR_SHORT_TERM]
META_DOLLAR_BAR_MID_FEATURES = feature_info["meta"][DOLLAR_BAR_MID_TERM]
META_DOLLAR_BAR_LONG_FEATURES = feature_info["meta"][DOLLAR_BAR_LONG_TERM]
META_MODEL_SIDE_RES = feature_info["meta"]["model_res"]

META_RANGE_BAR_ALL = (
    META_RANGE_BAR_SHORT_FEATURES
    + META_RANGE_BAR_MID_FEATURES
    + META_RANGE_BAR_LONG_FEATURES
)
META_DOLLAR_BAR_ALL = (
    META_DOLLAR_BAR_SHORT_FEATURES
    + META_DOLLAR_BAR_MID_FEATURES
    + META_DOLLAR_BAR_LONG_FEATURES
)
META_ALL = META_RANGE_BAR_ALL + META_DOLLAR_BAR_ALL + META_MODEL_SIDE_RES

RANGE_BAR_THRESHOLD_SHORT = 0.0045
RANGE_BAR_THRESHOLD_MID = 0.009
RANGE_BAR_THRESHOLD_LONG = 0.018

DOLLAR_BAR_THRESHOLD_SHORT = 39951050.90908544
DOLLAR_BAR_THRESHOLD_MID = 111681345.0640343
DOLLAR_BAR_THRESHOLD_LONG = 279657350.36359805
